config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :categories
  resources :transactions

  root to: "transactions#dashboard"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy

  validates :name,:bank,:initial_balance, presence: true

  # Validação de valores numéricos
  validates :limit, :initial_balance, numericality: {  greater_than_or_equal_to: 0 }, allow_nil: true

  # Validação de comprimento
  validates :last_digits, length: { minimum: 4,maximum: 4 }, allow_nil: true

  def total_balance
    value = initial_balance.to_f + transactions.sum(:amount)
     ActionController::Base.helpers.number_with_precision(value, precision: 2, separator: ",", delimiter: ".")
  end
  private

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
 belongs_to :user, optional: true
has_many :transactions, dependent: :nullify

validates :name, presence: true
validates :is_income, inclusion: { in: [true, false] }
validates :color, format: { with: /\A#(?:[0-9a-fA-F]{3}){1,2}\z/, message: "deve ser um código hexadecimal válido" }

# Categoria global se user_id for nil
scope :global, -> { where(user_id: nil) }
scope :for_user, ->(user_id) { where(user_id: user_id).or(global) }

ICONS = %w[💰 🛒 🍔 🚗 📈 🏠 🎓 💳]


validates :icon, inclusion: { in: ICONS }

end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :category
  belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[show edit update destroy]
  def index
    @accounts = Account.all
  end

  def show
  end

  def new
    @account = Account.new
    render :form
  end

  def create
    # @user = current_user
     @user = User.first
    @account = Account.new(account_params)
    @account.user = @user
    if @account.save
      redirect_to account_path(@account)
      flash[:alert] = "Conta criada com sucesso."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
     render :form
  end

  def update
    # @user = current_user
     @user = User.first
    @account = Account.new(account_params)
    @account.user = @user
    if @account.save
      redirect_to account_path(@account)
      flash[:alert] = "Conta alterada com sucesso."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @account.destroy
    flash[:alert] = "Conta excluída com sucesso."

    redirect_to accounts_path()
  end

  private

  # Permits account parameters
  def account_params
    params.require(:account).permit( :name, :card_type, :bank, :initial_balance, :limit, :last_digits,:due_day)
  end

  def set_account
    @account = Account.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  # include Pundit::Authorization

  # # Pundit: allow-list approach
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "Você não tem autorização para acessar essa página."
  #   redirect_to(root_path)
  # end

  private

  # def skip_pundit?
  #   devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :cpf, :role])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address, :cpf, :role])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
    render :form
  end

  def create

    @category = Category.new(category_params)
    @category.user = @user

    if @category.save
      redirect_to category_path(@category)
      flash[:alert] = "Categoria criada com sucesso."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
     render :form
  end

  def update
    @category = Category.new(category_params)
    @category.user = @user
    if @category.save
      redirect_to category_path(@category)
      flash[:alert] = "Categoria alterada com sucesso."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy
    flash[:alert] = "Categoria excluída com sucesso."

    redirect_to categorys_path()
  end

  private

  # Permits category parameters
  def category_params
    params.require(:category).permit( :name, :icon, :is_income, :color, :date, :user_id)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]
  def index
    @transactions = Transaction.all
  end

  def show
  end

  def new
    @transaction = Transaction.new
    @categories = Category.all
    render :form
  end

  def create
    @categories = Category.all
    @account = Account.first
    @transaction = Transaction.new(transaction_params)
    @transaction.account = @account

    if @transaction.save
      redirect_to transaction_path(@transaction)
      flash[:alert] = "Conta criada com sucesso."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @categories = Category.all
     render :form
  end

  def update
    @categories = Category.all
    @account = Account.first
    @transaction = Transaction.find(params[:id])
    @transaction.account = @account

    if @transaction.update(transaction_params)
      flash[:alert] = "Transação atualizada com sucesso."
      redirect_to transaction_path(@transaction)
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @transaction.destroy
    flash[:alert] = "Conta excluída com sucesso."

    redirect_to transactions_path()
  end

  private

  # Permits transaction parameters
  def transaction_params
    params.require(:transaction).permit( :amount, :description, :to_whom, :payment_method, :date, :category_id)
  end

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/form.html.erb
<div class="container  mt-4">
  <%= link_to accounts_path, class: 'bg-black text-white text-decoration-none p-2' do %>
    <i class='fa-solid fa-circle-left'></i>volta
  <% end %>
  <h1 class="pb-3 text-center"><%= @account.persisted? ? 'Editar Conta' : 'Nova Conta' %></h1>
  <div class="mx-3">
    <%= form_with model: @account, local: true do |f| %>
      <div class="grid grid-cols-3">
        <div class="mx-auto">
          <%= f.label :name, "Nome", class: "block mb-2 text-sm font-medium text-gray-900 " %>
          <%= f.text_field :name,
                          class: "m-2 border border-gray-400 text-gray-900 text-sm rounded-lg block  p-2.5 ",
                          placeholder: "Principal, CC, ...", required: true %>
        </div>
        <div class="mx-auto">
          <%= f.label :bank, "Banco", class: "block mb-2 text-sm font-medium text-gray-900 " %>
          <%= f.text_field :bank, class: "border border-gray-400 m-2 text-sm rounded-lg p-2.5",  placeholder: "BB, C6, Nubank,...", required: true  %>
        </div>
        <div class="mx-auto">
          <%= f.label :initial_balance, "Saldo inicial", class: "block mb-2 text-sm font-medium text-gray-900 " %>
          <%= f.number_field :initial_balance, step: 0.01, class: "border border-gray-400 m-2  text-sm rounded-lg p-2.5", placeholder: "0,00", required: true%>
        </div>
          <div class="mx-auto">
          <%= f.label :card_type, "Categoria do Cartão", class: "block mb-2 text-sm font-medium text-gray-900 " %>
          <%= f.text_field :card_type, class: "border border-gray-400 m-2 text-sm rounded-lg p-2.5",  placeholder: "Gold,..."  %>
        </div>
        <div class="mx-auto">
          <%= f.label :last_digits, "Ultimos digitos", class: "block mb-2 text-sm font-medium text-gray-900 " %>
          <%= f.text_field :last_digits, class: "border border-gray-400 m-2 text-sm rounded-lg p-2.5",  placeholder: "XXXX"  %>
        </div>
        <div class="mx-auto">
          <%= f.label :limit, "Limite no cartão", class: "block mb-2 text-sm font-medium text-gray-900 " %>
          <%= f.number_field :limit, step: 0.01, class: "border border-gray-400 m-2  text-sm rounded-lg p-2.5", placeholder: "100,00"%>
        </div>
          <div class="mx-auto">
          <%= f.label :due_day, "Data de vencimento", class: "block mb-2 text-sm font-medium text-gray-900 " %>
          <%= f.date_field :due_day, step: 0.01, class: "border border-gray-400 m-2  text-sm rounded-lg p-2.5", placeholder: "100,00"%>
        </div>
      <div class="col-span-3 mx-auto my-2">
        <%= f.button :submit, class: "text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300  rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 " %>
      </div>
      </div>
    <% end %>
  </div>
</div>

app/views/accounts/index.html.erb
<div class="container">
  <h1 class="text-center">Minhas Contas
    <%= link_to new_account_path(), class: "text-gray-500" do %>
      <i class="fa-solid fa-circle-plus"></i>
      <% end %>
  </h1>


  <div class ="flex mt-4 gap-10 ">
    <%@accounts.each  do |account| %>
      <div class="max-w-sm min-w-xs bg-white border border-gray-200 rounded-lg shadow-sm ">
        <div class="p-5 flex flex-col justify-between h-full">
          <div>
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 "><%= account.name %> - <%= account.bank %></h5>
            <p class="mb-3 font-normal text-gray-700 ">Saldo Total: R$ <%= account.total_balance %></p>
            <p class ="text-gray-700">Últimas Transações
              <ul>
                <% account.transactions.order(created_at: :desc).limit(5).each do |transaction| %>
                  <li><%= transaction.description %> : <%= content_tag :span, number_to_currency(transaction.amount, unit: "R$", separator: ",", delimiter: "."), class: transaction.amount.negative? ? "text-red-600" : "text-green-600" %></li>
                <% end %>
              </ul>
            </p>
          </div>
          <div class="mt-4">
            <%= link_to account_path(account), class: " inline-flex items-center px-3 py-2  text-center text-white bg-blue-600 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 " do %>
              Ver mais &nbsp <i class="fa-solid fa-arrow-right"></i>
            <% end %>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/accounts/show.html.erb
<div>
<%= link_to accounts_path, class: 'bg-black text-white text-decoration-none p-2' do %>
    <i class='fa-solid fa-circle-left'></i>volta
  <% end %>
<h1>Accounts#show</h1>
<p><%= @account.name %></p>
<p><%= @account.bank %></p>
<p><%= @account.initial_balance %></p>
<p>cartao</p>
<p>tipo:<%= @account.card_type %></p>
<p>Nº:<%= @account.last_digits %></p>
<p>limite:<%= @account.limit %></p>
<%= link_to edit_account_path(@account), class: '' do %>
  <%= render ButtonComponent.new(label: "Edit") %>
  <% end %>
<%= link_to account_path(@account), data: { turbo_method: :delete , turbo_confirm: "Tem certeza que deseja apagar esta conta?" }, class: '' do %>
 <%= render ButtonComponent.new(label: "Apagar") %>
<% end %>
</div>

app/views/categories/form.html.erb
<div class="container  mt-4">
  <%= link_to categories_path, class: 'bg-black text-white text-decoration-none p-2' do %>
    <i class='fa-solid fa-circle-left'></i>volta
  <% end %>
  <h1 class="pb-3 text-center"><%= @category.persisted? ? 'Editar Conta' : 'Nova Conta' %></h1>
  <div class="mx-3">
    <%= form_with model: @category, local: true do |f| %>
      <div class="grid grid-cols-4 gap-4 w-full ">
        <div class="mx-auto">
          <%= f.label :name, "Nome da Categoria", class: "block mb-2 text-sm font-medium text-gray-900" %>
          <%= f.text_field :name, class: "border border-gray-400 m-2 text-sm rounded-lg p-2.5",  placeholder: "Energia, lanche, estudos" %>
        </div>
        <div class="mx-auto">
          <%= f.label :is_income, "Tipo", class: "block mb-2 text-sm font-medium text-gray-900" %>
          <%= f.select :is_income, [["Entrada", true], ["Saída", false]], {}, class: "border border-gray-400 m-2 text-sm rounded-lg p-2.5" %>
        </div>
        <div class="mx-auto">
          <%= f.label :icon, "Ícone", class: "block mb-2 text-sm font-medium text-gray-900" %>
          <%= f.select :icon, Category::ICONS.map { |i| [i, i] }, {}, class: "border border-gray-400 m-2 text-sm rounded-lg p-2.5 text-lg" %>
        </div>
        <div class="mx-auto">
          <%= f.label :color, "Cor da Categoria", class: "block mb-2 text-sm font-medium text-gray-900" %>
          <%= f.color_field :color, class: "border border-gray-400 m-2 w-16 h-10 p-0.5  cursor-pointer rounded-lg  " %>
        </div>

        </div>
      <div class="col-span-3 mx-auto my-2">
        <%= f.button :submit, class: "text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300  rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 " %>
      </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<div>
<h1>Categories#index</h1>

<%@categories.each  do |category| %>
<p><%= category.name %>-<%= category.is_income ? "Entrada" : "Saída" %></p>
<%= link_to "acessar",category_path(category), class: "text-red-700 " %>
<% end %>
<p>
<%= link_to new_category_path() do %>
  <%= render ButtonComponent.new(label: "Criar Categoria") %>
  <% end %>
</p>
</div>

app/views/categories/show.html.erb
<div>
<%= link_to categories_path, class: 'bg-black text-white text-decoration-none p-2' do %>
    <i class='fa-solid fa-circle-left'></i>volta
  <% end %>
<h1>Categories#show</h1>
<p style="background-color: <%= @category.color %>; color: white;"><%= @category.name %>- <%= @category.icon %></p>
<p><%= @category.is_income ? "Entrada" : "Saída" %></p>
<p>criado:<%= @category&.user&.name %></p>

<%= link_to edit_category_path(@category), class: '' do %>
  <%= render ButtonComponent.new(label: "Edit") %>
  <% end %>
<%= link_to category_path(@category), data: { turbo_method: :delete , turbo_confirm: "Tem certeza que deseja apagar esta conta?" }, class: '' do %>
 <%= render ButtonComponent.new(label: "Apagar") %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoneyControl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <link rel="shortcut icon" type="image/x-icon" href="/assets/icon.ico">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <main class="container mx-auto mt-10 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="border-gray-200 bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
      <%= link_to root_path, class: "flex items-center space-x-3" do %>
        <img src="<%= asset_path('$$$.png') %>" class="h-8" alt="Flowbite Logo" />
        <h2 class="self-center italic text-white">MoneyControl</h2>
      <% end %>
  <div class="flex items-center order-2 space-x-0 ">
    <% if current_user.presence %>
     <div class="relative ml-3">
        <button id="user-menu-button" type="button" class="relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" onclick="document.getElementById('user-dropdown').classList.toggle('hidden')">
          <p class="block py-2 px-3 text-gray-200 rounded-full"><%= current_user&.name %></p>
          <img class="size-10 rounded-full" src="<%= asset_path('sem_foto.jpg') %>" alt="">
        </button>

        <div id="user-dropdown" class="hidden absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black/5">
          <%= link_to edit_user_registration_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" do %>
                <i class="fa-solid fa-user"></i> </i> Minha Conta
                <% end %>
          <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" do %>
                <i class="fa-solid fa-right-from-bracket"></i> Sair
                <% end %>
        </div>
      </div>
    <% end %>

  </div>
  <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
    <ul class="flex font-medium p-0 mt-0 border rounded-lg  flex-row">
      <li>
        <%= link_to "Home",root_path(), class: "block py-2 px-3 text-gray-500 rounded-sm hover:bg-gray-100 " %>
      </li>
      <li>
        <%= link_to "Contas",accounts_path(), class: "block py-2 px-3 text-gray-500 rounded-sm hover:bg-gray-100 " %>
      </li>
      <li>
        <%= link_to "Transações",transactions_path(), class: "block py-2 px-3 text-gray-500 rounded-sm hover:bg-gray-100 " %>
      </li>
      <li>
       <%= link_to "Categorias",categories_path(), class: "block py-2 px-3 text-gray-500 rounded-sm hover:bg-gray-100 " %>
      </li>
    </ul>
  </div>
  </div>
</nav>

app/views/transactions/dashboard.html.erb
<div>
  <h1>Dashboard</h1>
</div>

app/views/transactions/form.html.erb
<div class="container  mt-4">
  <%= link_to transactions_path, class: 'bg-black text-white text-decoration-none p-2' do %>
    <i class='fa-solid fa-circle-left'></i>volta
  <% end %>
  <h1 class="pb-3 text-center"><%= @transaction.persisted? ? 'Editar Conta' : 'Nova Conta' %></h1>
  <div class="mx-3">
    <%= form_with model: @transaction, local: true do |f| %>
      <div class="grid grid-cols-3">
        <div class="mx-auto">
          <%= f.label :amount, "Valor", class: "block mb-2 text-sm font-medium text-gray-900 " %>
          <%= f.number_field :amount, step: 0.01, class: "border border-gray-400 m-2  text-sm rounded-lg p-2.5", placeholder: "0,00", required: true%>
        </div>
          <div class="mx-auto">
          <%= f.label :description, "Descrição", class: "block mb-2 text-sm font-medium text-gray-900 " %>
          <%= f.text_field :description, class: "border border-gray-400 m-2 text-sm rounded-lg p-2.5",  placeholder: "Energia, lanche, estudos"  %>
        </div>
        <div class="mx-auto">
          <%= f.label :to_whom, "Recebedor/Pagador", class: "block mb-2 text-sm font-medium text-gray-900 " %>
          <%= f.text_field :to_whom, class: "border border-gray-400 m-2 text-sm rounded-lg p-2.5",  placeholder: "Banco X, Amazon..."  %>
        </div>
        <div class="mx-auto">
          <%= f.label :payment_method, "Método de pagamento", class: "block mb-2 text-sm font-medium text-gray-900 " %>
          <%= f.text_field :payment_method, class: "border border-gray-400 m-2  text-sm rounded-lg p-2.5", placeholder: "Débito,PIX,.."%>
        </div>
          <div class="mx-auto">
          <%= f.label :date, "Data", class: "block mb-2 text-sm font-medium text-gray-900 " %>
          <%= f.date_field :date, step: 0.01, class: "border border-gray-400 m-2  text-sm rounded-lg p-2.5", placeholder: "100,00"%>
        </div>
        <div class="mx-auto">
          <%= f.label :category_id, "Selecione a Categoria", class: "block mb-2 text-sm font-medium text-gray-900" %>
          <%= f.select :category_id, @categories.collect { |c| [c.name, c.id] }, { prompt: "Selecione" }, class: "border border-gray-400 m-2 text-sm rounded-lg p-2.5" %>
        </div>
      <div class="col-span-3 mx-auto my-2">
        <%= f.button :submit, class: "text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300  rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 " %>
      </div>
      </div>
    <% end %>
  </div>
</div>

app/views/transactions/index.html.erb
<div>
<h1>transações</h1>
<%@transactions.each  do |transaction| %>
<p><%= transaction.amount %>-<%= transaction.description %></p>
<%= link_to "acessar",transaction_path(transaction), class: "text-red-700 " %>
<% end %>
<p>
<%= link_to new_transaction_path() do %>
  <%= render ButtonComponent.new(label: "Adicionar transação") %>
  <% end %>
</p>
</div>

app/views/transactions/show.html.erb
<div>
<%= link_to transactions_path, class: 'bg-black text-white rounded-lg text-decoration-none p-2' do %>
    <i class='fa-solid fa-circle-left'></i>volta
  <% end %>
<h1>transactions#show</h1>
<p>R$<%= @transaction.amount %></p>
<p>D: <%= @transaction.description %></p>
<p><%= @transaction.date %></p>
<p>R/P: <%= @transaction.to_whom %></p>
<p>metodo:<%= @transaction.payment_method %></p>
<p>Conta:<%= @transaction.account.name %>-<%= @transaction.account.bank %></p>
<p>Categoria:<%= @transaction.category.name %></p>
<%= link_to edit_transaction_path(@transaction), class: '' do %>
  <%= render ButtonComponent.new(label: "Edit") %>
  <% end %>
<%= link_to transaction_path(@transaction), data: { turbo_method: :delete , turbo_confirm: "Tem certeza que deseja apagar esta transação?" }, class: '' do %>
 <%= render ButtonComponent.new(label: "Apagar") %>
<% end %>
</div>